server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: note

